import * as assert from 'node:assert/strict';
import { validateResearchFindings } from '../src/research/research.contract';
import { buildResearchReport, reviewResearch } from '../src/research/research-review';
import { RunTopologyService } from '../src/runs/services/run-topology.service';
import { NodeExecutorService } from '../src/runs/services/node-executor.service';
import { VariableResolverService } from '../src/runs/services/variable-resolver.service';

const source = { url: 'https://example.org/report', title: 'Original report', publishedAt: null, accessedAt: '2026-09-25T10:00:00Z', type: 'government', evidence: 'The measured value was 42.', role: 'supports' } as const;
const finding = { id: 'f-1', claim: 'The measured value was 42.', evidence: 'The report states the measured value was 42.', sources: [source], confidence: 0.8, limitations: '', researchArea: 'market', questionIds: ['q-1'] };
const questions = [{ id: 'q-1', question: 'What was measured?' }, { id: 'q-2', question: 'What changed?' }];
assert.equal(validateResearchFindings([finding]).valid, true);
const broken: any = { ...finding, id: 'f-2', confidence: 1.4, sources: [{ ...source, url: 'not a URL', type: 'blog', accessedAt: '', evidence: 'x'.repeat(10) }] };
const invalid = validateResearchFindings([broken], 5);
assert.equal(invalid.valid, false);
assert.deepEqual(invalid.findings, []);
for (const path of ['confidence', 'sources[0].url', 'sources[0].type', 'sources[0].accessedAt', 'sources[0].evidence']) assert.ok(invalid.errors.some(e => e.path.endsWith(path)), path);
assert.ok(validateResearchFindings([{ ...finding, sources: [] }]).errors.some(e => e.code === 'missing_provenance'));
assert.ok(validateResearchFindings([{ ...finding, sources: [{ ...source, role: 'qualifies' }] }]).errors.some(e => e.code === 'unsupported_claim'));
assert.ok(validateResearchFindings([finding, finding]).errors.some(e => e.code === 'duplicate'));
const review = reviewResearch({ findings: [finding], questions });
assert.equal(review.decision, 'needs_more_research');
assert.equal(review.coverage[0].status, 'answered');
assert.equal(review.coverage[1].status, 'unanswered');
assert.equal(review.gaps[0].questionId, 'q-2');
const conflict = reviewResearch({ findings: [finding, { ...finding, id: 'f-2', questionIds: ['q-2'], contradictsFindingIds: ['f-1'] }], questions });
assert.equal(conflict.contradictions[0].findingIds[1], 'f-1');
assert.equal(conflict.decision, 'needs_more_research');
const weak = reviewResearch({ findings: [{ ...finding, sources: [{ ...source, type: 'other' as const }] }], questions: questions.slice(0, 1) });
assert.equal(weak.weakSources[0].findingId, 'f-1');
assert.equal(weak.decision, 'needs_more_research');
const invalidReview = reviewResearch({ findings: [broken], questions });
assert.equal(invalidReview.decision, 'revise_findings');
assert.ok(invalidReview.validationErrors.length > 0);
const limited = reviewResearch({ findings: [finding], questions, reviewCycle: 3, maxReviewCycles: 3 });
assert.equal(limited.status, 'incomplete_needs_human_review');
const passed = reviewResearch({ findings: [finding], questions: questions.slice(0, 1) });
assert.equal(passed.decision, 'pass');
const topology = new RunTopologyService();
const node = { id: 'review', type: 'research-review', data: {} };
const edges = ['pass', 'needs_more_research', 'revise_findings', 'incomplete_needs_human_review'].map(sourceHandle => ({ sourceHandle, target: sourceHandle }));
assert.deepEqual(topology.resolveNextTargets(node, passed, edges), ['pass']);
assert.deepEqual(topology.resolveNextTargets(node, limited, edges), ['incomplete_needs_human_review']);
const report = buildResearchReport([finding], [{ text: 'Conclusion', findingIds: ['f-1'] }]);
assert.equal(report.conclusions[0].sources[0].url, source.url);
assert.equal(report.conclusions[0].sources[0].title, source.title);
assert.equal(report.conclusions[0].findingIds[0], 'f-1');
assert.equal(buildResearchReport([{ ...finding, confidence: 0.3 }], [{ text: 'Estimate', findingIds: ['f-1'] }]).conclusions[0].label, 'low_confidence');
const executor = new NodeExecutorService(new VariableResolverService(), {} as any, {} as any, {} as any);
const reviewNode = { id: 'review', type: 'research-review', data: { config: { findings: [finding], questions, maxReviewCycles: 2 } } };
const context: Record<string, any> = {};
async function testCycles() {
  const first = await executor.executeNode(reviewNode, {}, context, {}, 'run-1');
  const second = await executor.executeNode(reviewNode, {}, context, {}, 'run-1');
  assert.equal(first.reviewCycle, 1);
  assert.equal(second.reviewCycle, 2);
  assert.equal(second.status, 'incomplete_needs_human_review');
  console.log('Research contract and reviewer tests passed');
}
testCycles().catch(error => { console.error(error); process.exitCode = 1; });
